name: IPA Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-14

    strategy:
      matrix:
        platform: ['iOS']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Fetch Commit Info
      id: commitinfo
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Resolve Swift Package Dependencies
      run: |
        swift package resolve

    - name: Build IPA
      run: |
        xcodebuild clean -project "./App/Mochi.xcodeproj" \
                         -scheme Mochi \
                         -configuration Release \
                         -destination generic/platform=${{ matrix.platform }} \
                         archive -archivePath "build/Mochi.${{ matrix.platform }}.xcarchive" \
                         CODE_SIGN_IDENTITY="" \
                         CODE_SIGNING_REQUIRED=NO \
                         CODE_SIGNING_ALLOWED=NO \
                         -skipMacroValidation \
                         -verbose
        xcodebuild -exportArchive -archivePath "build/Mochi.${{ matrix.platform }}.xcarchive" \
                                  -exportOptionsPlist exportOptions.plist \
                                  -exportPath "build"

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mochi.${{ steps.commitinfo.outputs.sha_short }}.${{ matrix.platform }}.ipa
        path: build/*.ipa
        if-no-files-found: error
