name: cd

on:
  workflow_run:
    workflows: 
      - ci
    branches:
      - dev
    types:
      - completed

jobs:
  build-publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Brew Install Dependencies
        run: |
          brew install cocogitto xcbeautify

      - run: fastlane deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}