name: Build and Export Unsigned IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4.0'

    - name: Build and Export IPA
      run: |
        xcodebuild clean -project App/Mochi.xcodeproj -scheme Mochi -configuration Release
        xcodebuild archive -project App/Mochi.xcodeproj -scheme Mochi -configuration Release -archivePath $PWD/build/Mochi.xcarchive -skipMacroValidation
        xcodebuild -exportArchive -archivePath $PWD/build/Mochi.xcarchive -exportOptionsPlist App/exportOptions.plist -exportPath $PWD/build

    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mochi.ipa
        path: build/Mochi.ipa
